/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenCentral()
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-data-jpa:2.7.8")
    api("org.springframework.data:spring-data-jdbc:1.1.4.RELEASE")
    api("org.springframework.boot:spring-boot-starter-web:2.7.8")
    api("net.datafaker:datafaker:1.5.0")
    api("com.mysql:mysql-connector-j:8.0.32")
    api("org.projectlombok:lombok:1.18.24")
    api("com.google.firebase:firebase-admin:7.0.0")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.7.8")
    runtimeOnly("com.h2database:h2:2.1.214")
    runtimeOnly("org.mariadb.jdbc:mariadb-java-client:3.0.10")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.8")
    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
}

group = "in.ac.skcet"
version = "0.0.1-SNAPSHOT"
description = "Event-Manager"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
