INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Dr. M. Sujaritha',9524969345,'sujaritham@skcet.ac.in ','II CSE A','sujaritham','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Dr.V.Vijeyakaveri',9445006897,'vijeyakaveriv@skcet.ac.in ','III CSE C','vijeyakaveriv','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Dr.P.Mohan Kumar',9884217019,'mohankumarp@skcet.ac.in ','II CSE B','mohankumarp','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Dr.G.Vijaya',9003925163,'vijayag@skcet.ac.in','IV CSE A','vijayag','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Dr.D.Rasi',9442456603,'rasid@skcet.ac.in','II CSE C','rasid','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Dr. T.Latha Maheswari',9003311976,'lathamaheswari@skcet.ac.in','II CSE  A','lathamaheswari','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Dr.S.Oswalt Manoj',9843259672,'oswaltmanoj@skcet.ac.in','III CSE A','oswaltmanoj','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Dr. N. Kousika',9791917254,'kousika@skcet.ac.in ','IV CSE C','kousika','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Dr.G.Sathish Kumar',9962225615,'sathishkumarg@skcet.ac.in','II CSE A','sathishkumarg','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Ms. V.R. Azhaguramyaa',9942796017,'azhaguramyaa@skcet.ac.in','III CSE A','azhaguramyaa','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Ms. N. Pooranam',7373950869,'pooranamn@skcet.ac.in','IV CSE B','pooranamn','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Ms. K.M. Majidha Fathima',9952905750,'majidhafathimakm@skcet.ac.in','IV CSE B','majidhafathimakm','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Ms. A. Priya',9629680614,'priyaa@skcet.ac.in','II CSE B','priyaa','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Ms.G.Renugadevi',9840569414,'grenugadevi@skcet.ac.in','III CSE C','grenugadevi','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Mr.M.Vengateshvaran',9940857074,'vengateshwaranm@skcet.ac.in','III CSE B','vengateshwaranm','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('Ms.Vajitha Nazreen S',7868076014,'vajithanazreens@skcet.ac.in','II CSE C','vajithanazreens','Teacher');
INSERT INTO staff (name,mobile,mail,class_code,staff_id,dtype) VALUES ('S.Abirami',9943317689,'abiramis@skcet.ac.in ','III  CSE B','abiramis','Teacher');
